# Intro to Pandas
___

**pandas** provides data structures and data manipulation tools designed for fast & easy data cleaning and analysis.

pandas adopts array-based computing from NumPy, but is designed for **tabular** or **heterogenous** data.

pandas has two primary data structures:

- **Series** - one-dimensional array-like object with a sequence of values having the same datatype
- **DataFrame** - rectangular table of data with ordered collection of columns, each of which can be a different value type

In [1]:
#As allways we import pandas and numpy
import pandas as pd
import numpy as np

### Series

Has a sequence of values (all the same datatype) and an associated array of data labels called its **index**. If not specified otherwise, the index values are sequential integers.

pandas can automatically determine datatype of values when a Series is created, but datatype can also be specified.

A Series is like a fixed-length, ordered dict with a mapping of index values to data values.

The array representation and index object of a Series can be accessed via its **values** and **index** attributes.

Problem 1: Create a series 4 numerical values. Print the series, the values and the index of the series.

In [2]:
num_series = pd.Series([1, 2, 3, 4])
print(num_series)
print(num_series.values)
print(num_series.index)

0    1
1    2
2    3
3    4
dtype: int64
[1 2 3 4]
RangeIndex(start=0, stop=4, step=1)

Problem 2: Create a new series with the same values but with string values for the index. Select and print out one of the values in the series with the index.

In [3]:
new_series = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
print(new_series['b'])

2

Problem 3: You can also create a series from a python dict. Create a dict called `states_dict` with the state name as the key and the number as the value.
'Ohio' 35000
'Texas' 71000
'Oregon' 16000 
'Utah' 5000
Use the dict `states_dict` to create a series called `states_series`.

In [4]:
states_dict = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
states_series = pd.Series(states_dict)
print(states_series)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Problem 4: Updated the index of `state_series` to be the abbreviation of the state names. Do this in place.

In [5]:
print("Renaming all of the indices:")
states_series.index = ['OH', 'TX', 'OR', 'UT']
print(states_series)
print("\nAnd now to rename specific indices:")
states_series.rename(index = {'OH': 'OH MYYY!', 'UT': 'UTWO'}, inplace = True)
print(states_series)

Renaming all of the indices:
OH    35000
TX    71000
OR    16000
UT     5000
dtype: int64

And now to rename specific indices:
OH MYYY!    35000
TX          71000
OR          16000
UTWO         5000
dtype: int64

### DataFrame

A pandas DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type.

Sort of a dict of Series all sharing the same index.

- DataFrames have both row and column indices
- DataFrames are physically 2D, but can represent higher-dimensional data using hierarchical indexing
- DataFrame rows are sometimes referred to as axis=0
- DataFrame columns are sometimes referred to as axis=1


You can create DataFrames from dicts as well.

In [6]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 2002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
      }

df = pd.DataFrame(data)
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

Problem 5: Update the index of the DataFrame df to be the words for each number. i.e. 1 -> one

In [7]:
df.rename(index={0: 'zero', 1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}, inplace = True)
df

        state  year  pop
zero     Ohio  2000  1.5
one      Ohio  2001  1.7
two      Ohio  2002  3.6
three  Nevada  2001  2.4
four   Nevada  2002  2.9
five   Nevada  2003  3.2

Problem 6: Figure out two ways to access a column from df. Output the results.

In [8]:
print("We can access the columns by their names as an extension, like 'df.state':")
print(df.state)
print("NB: This method will not work if the column name has white space, or conflicts with a DataFrame method name.")
print("\nOr we can use the name of the column as an index, such as 'df['state']':")
print(df['state'])

We can access the columns by their names as an extension, like 'df.state':
zero       Ohio
one        Ohio
two        Ohio
three    Nevada
four     Nevada
five     Nevada
Name: state, dtype: object
NB: This method will not work if the column name has white space, or conflicts with a DataFrame method name.

Or we can use the name of the column as an index, such as 'df['state']':
zero       Ohio
one        Ohio
two        Ohio
three    Nevada
four     Nevada
five     Nevada
Name: state, dtype: object

Problem 7: Figure out two ways to access a row from df. Output the results.

In [9]:
print("To access rows, we can use 'df.loc['zero']':")
print(df.loc['zero'])
print("\nOr we can use the row index, 'df.iloc[0]':")
print(df.iloc[0])

To access rows, we can use 'df.loc['zero']':
state    Ohio
year     2000
pop       1.5
Name: zero, dtype: object

Or we can use the row index, 'df.iloc[0]':
state    Ohio
year     2000
pop       1.5
Name: zero, dtype: object

Problem 8: Add a new column to your dataframe called 'rating' with the values `[5,4,3,2,1,0]`

In [10]:
df['rating'] = [5, 4, 3, 2, 1, 0]
df

        state  year  pop  rating
zero     Ohio  2000  1.5       5
one      Ohio  2001  1.7       4
two      Ohio  2002  3.6       3
three  Nevada  2001  2.4       2
four   Nevada  2002  2.9       1
five   Nevada  2003  3.2       0

Problem 9: Create another column called `nonsense` that is the rating multiplied by the pop.

In [11]:
df['nonsense'] = df['rating'] * df['pop']
df

        state  year  pop  rating  nonsense
zero     Ohio  2000  1.5       5       7.5
one      Ohio  2001  1.7       4       6.8
two      Ohio  2002  3.6       3      10.8
three  Nevada  2001  2.4       2       4.8
four   Nevada  2002  2.9       1       2.9
five   Nevada  2003  3.2       0       0.0

Problem 10: Create three series using using numpy.

* series_numerical: The values 0-4 with index a-e
* series_zeros: All zeros with index a-e
* series_random: 5 random numbers qith index a-e

DataFrame called `numeric_df` from these three series. Each series will be a row and the columns will be a-e.

In [24]:
indices = ['a', 'b', 'c', 'd', 'e']
series_numerical = pd.Series(np.arange(5), index = indices)
series_zeros = pd.Series(np.zeros(5), index = indices)
series_random = pd.Series(np.random.randn(5), index = indices)
numeric_df = pd.DataFrame(columns = indices, data =(series_numerical, series_zeros, series_random))
numeric_df

          a        b         c         d         e
0  0.000000  1.00000  2.000000  3.000000  4.000000
1  0.000000  0.00000  0.000000  0.000000  0.000000
2  1.836282  0.66257 -1.140489 -0.631857 -0.438612

Problem 11: Transpose the DataFrame `numeric_df` so that the series become columns instead of rows. Save this to a variable called `transposed_numeric_df`. Rename the columns to `numerical`, `zeros`, and `random`.

In [30]:
transposed_numeric_df = numeric_df.T
new_indices = ['numerical', 'zeros', 'random']
transposed_numeric_df.columns = new_indices
print("New indices:", new_indices)
print("\nTransposed DataFrame compplete with new indices:")
print(transposed_numeric_df)
print()
print("Ensuring original DataFrame is unchanged:")
print(numeric_df)

New indices: ['numerical', 'zeros', 'random']

Transposed DataFrame compplete with new indices:
   numerical  zeros    random
a        0.0    0.0  1.836282
b        1.0    0.0  0.662570
c        2.0    0.0 -1.140489
d        3.0    0.0 -0.631857
e        4.0    0.0 -0.438612

Ensuring original DataFrame is unchanged:
          a        b         c         d         e
0  0.000000  1.00000  2.000000  3.000000  4.000000
1  0.000000  0.00000  0.000000  0.000000  0.000000
2  1.836282  0.66257 -1.140489 -0.631857 -0.438612

Problem 12: Output `transposed_numeric_df` ordered by `random` descending.

In [32]:
print("Sorting by 'random' column in descending order using .sort_values():")
print(transposed_numeric_df.sort_values(by = 'random', ascending = False))

Sorting by 'random' column in descending order using .sort_values():
   numerical  zeros    random
a        0.0    0.0  1.836282
b        1.0    0.0  0.662570
e        4.0    0.0 -0.438612
d        3.0    0.0 -0.631857
c        2.0    0.0 -1.140489

Problem 13: Select all rows from `transposed_numeric_df` where the column `numerical` is greater than 2.

In [34]:
print("Passing a condition to filter rows where 'numerical' > 2:")
print(transposed_numeric_df[transposed_numeric_df['numerical'] > 2])

Passing a condition to filter rows where 'numerical' > 2:
   numerical  zeros    random
d        3.0    0.0 -0.631857
e        4.0    0.0 -0.438612

Problem 14: Add a column called `random_5` that is the column random multiplied by 5. Select all rows from `transposed_numeric_df` where `numerical` is greater than `random_5`.

In [40]:
print("When calling a column that doesn't exist, a new column is created, and" \
      "\nwe can assign it values based on another column multiplied by a scalar.")
transposed_numeric_df['random_5'] = transposed_numeric_df['random'] * 5
print(transposed_numeric_df[transposed_numeric_df['numerical'] > transposed_numeric_df['random_5']])

When calling a column that doesn't exist, a new column is created, and
we can assign it values based on another column multiplied by a scalar.
   numerical  zeros    random  random_5
c        2.0    0.0 -1.140489 -5.702443
d        3.0    0.0 -0.631857 -3.159283
e        4.0    0.0 -0.438612 -2.193061

Problem 15: Add a column to transposed_numberic_df called `even` that is True when `numerical` is even and `False` when `numerical` is odd.

In [43]:
transposed_numeric_df['even'] = transposed_numeric_df['numerical'] % 2 == 0
transposed_numeric_df

   numerical  zeros    random  random_5   even
a        0.0    0.0  1.836282  9.181411   True
b        1.0    0.0  0.662570  3.312852  False
c        2.0    0.0 -1.140489 -5.702443   True
d        3.0    0.0 -0.631857 -3.159283  False
e        4.0    0.0 -0.438612 -2.193061   True

Problem 16: Add a column called `even_odd` that has the value `odd` when `numerical` is odd and `even` when `numerical` is even.

In [ ]:
transposed_numeric_df['even_odd'] = transposed_numeric_df['numerical'] % 2 == 0
transposed_numeric_df

   numerical  zeros    random  random_5   even  even_odd
a        0.0    0.0  1.836282  9.181411   True     False
b        1.0    0.0  0.662570  3.312852  False      True
c        2.0    0.0 -1.140489 -5.702443   True     False
d        3.0    0.0 -0.631857 -3.159283  False      True
e        4.0    0.0 -0.438612 -2.193061   True     False

Problem 17: Print out the sum of all columns.

Problem 18: Print out index of the row with the max value for each column. i.e. for `numerical` it will be the last row `e` because it has a value of 5.